const matrizFran = [
  {
    pronombre: "Je",
    presente: "veux",
    pasado: "voulais",
    futuro: "voudrai",
    complementario: "apprendre",
    sustantivo: "langlais",
  },
  {
    pronombre: "Tu",
    presente: "veux",
    pasado: "voulais",
    futuro: "voudras",
    complementario: "apprendre",
    sustantivo: "lespagnol",
  },
  {
    pronombre: "Il/Elle",
    presente: "veut",
    pasado: "voulait",
    futuro: "voudra",
    complementario: "apprendre",
    sustantivo: "le français",
  },
  {
    pronombre: "Nous",
    presente: "voulons",
    pasado: "voulions",
    futuro: "voudrons",
    complementario: "apprendre",
    sustantivo: "le chinois",
  },
  {
    pronombre: "Vous",
    presente: "voulez",
    pasado: "vouliez",
    futuro: "voudrez",
    complementario: "apprendre",
    sustantivo: "le japonais",
  },
  {
    pronombre: "Ils/Elles",
    presente: "veulent",
    pasado: "voulaient",
    futuro: "voudront",
    complementario: "apprendre",
    sustantivo: "lallemand",
  },
  {
    pronombre: "Je",
    presente: "voudrais",
    pasado: "voulais",
    futuro: "voudrai",
    complementario: "pratiquer",
    sustantivo: "le yoga",
  },
  {
    pronombre: "Tu",
    presente: "voudrais",
    pasado: "voulais",
    futuro: "voudras",
    complementario: "pratiquer",
    sustantivo: "le piano",
  },
  {
    pronombre: "Il/Elle",
    presente: "voudrait",
    pasado: "voulait",
    futuro: "voudra",
    complementario: "pratiquer",
    sustantivo: "la guitare",
  },
  {
    pronombre: "Nous",
    presente: "voudrions",
    pasado: "voulions",
    futuro: "voudrons",
    complementario: "pratiquer",
    sustantivo: "le chant",
  },
  {
    pronombre: "Vous",
    presente: "voudriez",
    pasado: "vouliez",
    futuro: "voudrez",
    complementario: "pratiquer",
    sustantivo: "la danse",
  },
  {
    pronombre: "Ils/Elles",
    presente: "voudraient",
    pasado: "voulaient",
    futuro: "voudront",
    complementario: "pratiquer",
    sustantivo: "la cuisine",
  },
  {
    pronombre: "Je",
    presente: "dois",
    pasado: "devais",
    futuro: "devrai",
    complementario: "améliorer",
    sustantivo: "les compétences de communication",
  },
  {
    pronombre: "Tu",
    presente: "dois",
    pasado: "devais",
    futuro: "devras",
    complementario: "améliorer",
    sustantivo: "lécriture",
  },
  {
    pronombre: "Il/Elle",
    presente: "doit",
    pasado: "devait",
    futuro: "devra",
    complementario: "améliorer",
    sustantivo: "la prise de parole en public",
  },
  {
    pronombre: "Nous",
    presente: "devons",
    pasado: "devions",
    futuro: "devrons",
    complementario: "améliorer",
    sustantivo: "les compétences en leadership",
  },
  {
    pronombre: "Vous",
    presente: "devez",
    pasado: "deviez",
    futuro: "devrez",
    complementario: "améliorer",
    sustantivo: "le travail déquipe",
  },
  {
    pronombre: "Ils/Elles",
    presente: "doivent",
    pasado: "devaient",
    futuro: "devront",
    complementario: "améliorer",
    sustantivo: "les compétences en résolution de problèmes",
  },
  {
    pronombre: "Je",
    presente: "ai besoin de",
    pasado: "avais besoin de",
    futuro: "aurai besoin de",
    complementario: "pratiquer",
    sustantivo: "le piano",
  },
  {
    pronombre: "Tu",
    presente: "as besoin de",
    pasado: "avais besoin de",
    futuro: "auras besoin de",
    complementario: "pratiquer",
    sustantivo: "le yoga",
  },
  {
    pronombre: "Il/Elle",
    presente: "a besoin de",
    pasado: "avait besoin de",
    futuro: "aura besoin de",
    complementario: "pratiquer",
    sustantivo: "la méditation",
  },
  {
    pronombre: "Nous",
    presente: "avons besoin de",
    pasado: "avions besoin de",
    futuro: "aurons besoin de",
    complementario: "pratiquer",
    sustantivo: "la pleine conscience",
  },
  {
    pronombre: "Vous",
    presente: "avez besoin de",
    pasado: "aviez besoin de",
    futuro: "aurez besoin de",
    complementario: "pratiquer",
    sustantivo: "la course à pied",
  },
  {
    pronombre: "Ils/Elles",
    presente: "ont besoin de",
    pasado: "avaient besoin de",
    futuro: "auront besoin de",
    complementario: "pratiquer",
    sustantivo: "la lecture",
  },
];

export default matrizFran;
