const matrizFrances = [
  // Pronombre JE
  {
    pronombre: "Je",
    verbo: "Ai besoin de",
    accion: "Manger",
    pronunciacion: "/ʒə ɛ bə.zwɛ̃ də/ (zhuh eh beh-zwahn duh) /mɑ̃ʒe/ (manzhe)",
    traduccion: "Necesito Comer",
  },
  {
    pronombre: "Je",
    verbo: "Aimerais",
    accion: "Courir",
    pronunciacion: "/ʒə ɛ.me.ʁɛ/ (zhuh eh-meh-reh) /ku.ʁiʁ/ (koo-reer)",
    traduccion: "Me Gustaría Correr",
  },
  {
    pronombre: "Je",
    verbo: "Dois",
    accion: "Courir",
    pronunciacion: "/ʒə dwa/ (zhuh dwa) /ku.ʁiʁ/ (koo-reer)",
    traduccion: "Debo Correr",
  },
  {
    pronombre: "Je",
    verbo: "Espère",
    accion: "Manger",
    pronunciacion: "/ʒə ɛs.pɛʁ/ (zhuh es-pehr) /mɑ̃ʒe/ (manzhe)",
    traduccion: "Espero Comer",
  },
  {
    pronombre: "Je",
    verbo: "Pense",
    accion: "Manger",
    pronunciacion: "/ʒə pɑ̃s/ (zhuh pahns) /mɑ̃ʒe/ (manzhe)",
    traduccion: "Pienso Comer",
  },
  {
    pronombre: "Je",
    verbo: "Peux",
    accion: "Courir",
    pronunciacion: "/ʒə pø/ (zhuh pu) /ku.ʁiʁ/ (koo-reer)",
    traduccion: "Puedo Correr",
  },
  {
    pronombre: "Je",
    verbo: "Aimerais",
    accion: "Dormir",
    pronunciacion: "/ʒə ɛ.me.ʁɛ/ (zhuh eh-meh-reh) /dɔʁ.miʁ/ (dor-meer)",
    traduccion: "Me Gustaría Dormir",
  },
  {
    pronombre: "Je",
    verbo: "Pense",
    accion: "Boire",
    pronunciacion: "/ʒə pɑ̃s/ (zhuh pahns) /bwaʁ/ (bwahr)",
    traduccion: "Pienso Beber",
  },
  {
    pronombre: "Je",
    verbo: "Peux",
    accion: "Dormir",
    pronunciacion: "/ʒə pø/ (zhuh pu) /dɔʁ.miʁ/ (dor-meer)",
    traduccion: "Puedes Dormir",
  },

  // Pronombre TU
  {
    pronombre: "Tu",
    verbo: "Aimerais",
    accion: "Dormir",
    pronunciacion: "/ty ɛ.me.ʁɛ/ (tyuh eh-meh-reh) /dɔʁ.miʁ/ (dor-meer)",
    traduccion: "Te Gustaría Dormir",
  },
  {
    pronombre: "Tu",
    verbo: "Aimerait",
    accion: "Voyager",
    pronunciacion: "/ty ɛ.mə.ʁɛ/ (tyuh eh-muh-reh) /vwa.jaʒe/ (vwa-ja-hay)",
    traduccion: "Él Gustaría Viajar",
  },
  {
    pronombre: "Tu",
    verbo: "As besoin de",
    accion: "Boire",
    pronunciacion: "/ty a bə.zwɛ̃ də/ (tyuh ah beh-zwahn duh) /bwaʁ/ (bwahr)",
    traduccion: "Necesitas Beber",
  },
  {
    pronombre: "Tu",
    verbo: "Dois",
    accion: "Dormir",
    pronunciacion: "/ty dwa/ (tyuh dwa) /dɔʁ.miʁ/ (dor-meer)",
    traduccion: "Debes Dormir",
  },
  {
    pronombre: "Tu",
    verbo: "Espères",
    accion: "Boire",
    pronunciacion: "/ty ɛs.pɛʁ/ (tyuh es-pehr) /bwaʁ/ (bwahr)",
    traduccion: "Tú Esperas Beber",
  },
  {
    pronombre: "Tu",
    verbo: "Penses",
    accion: "Boire",
    pronunciacion: "/ty pɑ̃s/ (tyuh pahns) /bwaʁ/ (bwahr)",
    traduccion: "Piensas Beber",
  },
  {
    pronombre: "Tu",
    verbo: "Peux",
    accion: "Dormir",
    pronunciacion: "/ty pø/ (tyuh pu) /dɔʁ.miʁ/ (dor-meer)",
    traduccion: "Puedes Dormir",
  },

  // Pronombre IL
  {
    pronombre: "Il",
    verbo: "Aimerait",
    accion: "Voyager",
    pronunciacion: "/il ɛ.mə.ʁɛ/ (eel eh-muh-reh) /vwa.jaʒe/ (vwa-ja-hay)",
    traduccion: "Él Gustaría Viajar",
  },
  {
    pronombre: "Il",
    verbo: "A besoin de",
    accion: "Écrire",
    pronunciacion: "/il a bə.zwɛ̃ də/ (eel ah beh-zwahn duh) /ekʁiʁ/ (ay-kree)",
    traduccion: "Él Necesita Escribir",
  },
  {
    pronombre: "Il",
    verbo: "Ont besoin de",
    accion: "Écrire",
    pronunciacion: "/il ɔ̃ bə.zwɛ̃ də/ (eel ohn beh-zwahn duh) /ekʁiʁ/ (ay-kree)",
    traduccion: "Ellos Necesitan Escribir",
  },
  {
    pronombre: "Il",
    verbo: "Pense",
    accion: "Écrire",
    pronunciacion: "/il pɑ̃s/ (eel pahns) /ekʁiʁ/ (ay-kree)",
    traduccion: "Él Piensa Escribir",
  },
  {
    pronombre: "Il",
    verbo: "Peut",
    accion: "Voyager",
    pronunciacion: "/il pø/ (eel pu) /vwa.jaʒe/ (vwa-ja-hay)",
    traduccion: "Él Puede Viajar",
  },
  {
    pronombre: "Il",
    verbo: "Veut",
    accion: "Étudier",
    pronunciacion: "/il vø/ (eel vuh) /etydje/ (ay-tyuh-dyuh)",
    traduccion: "Él Quiere Estudiar",
  },

  // Pronombre NOUS
  {
    pronombre: "Nous",
    verbo: "Avons besoin de",
    accion: "Travailler",
    pronunciacion:
      "/nu.z‿avɔ̃ bə.zwɛ̃ də/ (noo-zah-vawn beh-zwahn duh) /tʁa.va.je/ (trah-vah-zhe)",
    traduccion: "Nosotros Necesitamos Trabajar",
  },
  {
    pronombre: "Nous",
    verbo: "Aimerions",
    accion: "Danser",
    pronunciacion: "/nu.ze.mə.ʁjɔ̃/ (noo-zay-muh-ryawn) /dɑ̃.se/ (dahn-seh)",
    traduccion: "Nosotros Quisiéramos Bailar",
  },
  {
    pronombre: "Nous",
    verbo: "Devons",
    accion: "Danser",
    pronunciacion: "/nu də.vɔ̃/ (noo duh-vawn) /dɑ̃.se/ (dahn-seh)",
    traduccion: "Nosotros Debemos Bailar",
  },
  {
    pronombre: "Nous",
    verbo: "Espérons",
    accion: "Travailler",
    pronunciacion:
      "/nu.z‿es.pe.ʁɔ̃/ (noo-zay-speh-rohn) /tʁa.va.je/ (trah-vah-zhe)",
    traduccion: "Nosotros Esperamos Trabajar",
  },
  {
    pronombre: "Nous",
    verbo: "Pensons",
    accion: "Travailler",
    pronunciacion: "/nu pɑ̃.sɔ̃/ (noo pahnsawn) /tʁa.va.je/ (trah-vah-zhe)",
    traduccion: "Nosotros Pensamos Trabajar",
  },
  {
    pronombre: "Nous",
    verbo: "Pouvons",
    accion: "Danser",
    pronunciacion: "/nu pu.vɔ̃/ (noo poo-vawn) /dɑ̃.se/ (dahn-seh)",
    traduccion: "Nosotros Podemos Bailar",
  },

  // Pronombre VOUS
  {
    pronombre: "Vous",
    verbo: "Aimeriez",
    accion: "",
    pronunciacion: "/vu.ze.mi.ʁje/ (voo-zay-mee-ryeh)",
    traduccion: "Ustedes Gustarían",
  },
  {
    pronombre: "Vous",
    verbo: "Avez besoin de",
    accion: "Lire",
    pronunciacion: "/vu.z‿ave bə.zwɛ̃ də/ (voo-zay beh-zwahn duh) /liʁ/ (leer)",
    traduccion: "Ustedes Necesitan Leer",
  },
  {
    pronombre: "Vous",
    verbo: "Devez",
    accion: "",
    pronunciacion: "/vu də.ve/ (voo duh-veh)",
    traduccion: "Ustedes Deben",
  },
  {
    pronombre: "Vous",
    verbo: "Espérez",
    accion: "Lire",
    pronunciacion: "/vu.z‿es.pe.ʁe/ (voo-zay-speh-reh) /liʁ/ (leer)",
    traduccion: "Ustedes Esperan Leer",
  },
  {
    pronombre: "Vous",
    verbo: "Pensez",
    accion: "Lire",
    pronunciacion: "/vu pɑ̃.se/ (voo pahnsay) /liʁ/ (leer)",
    traduccion: "Ustedes Piensan Leer",
  },
  {
    pronombre: "Vous",
    verbo: "Pouvez",
    accion: "",
    pronunciacion: "/vu pu.ve/ (voo poo-veh)",
    traduccion: "Ustedes Pueden",
  },

  // Pronombre ILS
  {
    pronombre: "Ils",
    verbo: "Aimeraient",
    accion: "",
    pronunciacion: "/il ɛ.mə.ʁɛ/ (eel eh-muh-reh)",
    traduccion: "Ellos Gustarían",
  },
  {
    pronombre: "Ils",
    verbo: "Doivent",
    accion: "",
    pronunciacion: "/il dwav/ (eel dvahv)",
    traduccion: "Ellos Deben",
  },
  {
    pronombre: "Ils",
    verbo: "Ont besoin de",
    accion: "Écrire",
    pronunciacion: "/il ɔ̃ bə.zwɛ̃ də/ (eel ohn beh-zwahn duh) /ekʁiʁ/ (ay-kree)",
    traduccion: "Ellos Necesitan Escribir",
  },
  {
    pronombre: "Ils",
    verbo: "Pensent",
    accion: "Écrire",
    pronunciacion: "/il pɑ̃s/ (eel pahns) /ekʁiʁ/ (ay-kree)",
    traduccion: "Ellos Piensan Escribir",
  },
  {
    pronombre: "Ils",
    verbo: "Peuvent",
    accion: "",
    pronunciacion: "/il pøv/ (eel puv)",
    traduccion: "Ellos Pueden",
  },
  {
    pronombre: "Ils",
    verbo: "Veulent",
    accion: "Écrire",
    pronunciacion: "/il vœl/ (eel vuhl) /ekʁiʁ/ (ay-kree)",
    traduccion: "Ellos Quieren Escribir",
  },
];

export default matrizFrances;
