const matrizEng = [
  // Pronoun I
  {
    pronoun: "I",
    verb: "Need",
    action: "Eat",
    pronunciation: "/aɪ niːd/ (eye need) /iːt/ (eat)",
    translation: "I Need to Eat",
  },
  {
    pronoun: "I",
    verb: "Would like",
    action: "Run",
    pronunciation: "/aɪ wʊd laɪk/ (eye wood like) /rʌn/ (run)",
    translation: "I Would Like to Run",
  },
  {
    pronoun: "I",
    verb: "Must",
    action: "Run",
    pronunciation: "/aɪ mʌst/ (eye must) /rʌn/ (run)",
    translation: "I Must Run",
  },
  {
    pronoun: "I",
    verb: "Hope",
    action: "Eat",
    pronunciation: "/aɪ hoʊp/ (eye hope) /iːt/ (eat)",
    translation: "I Hope to Eat",
  },
  {
    pronoun: "I",
    verb: "Think",
    action: "Eat",
    pronunciation: "/aɪ θɪŋk/ (eye think) /iːt/ (eat)",
    translation: "I Think to Eat",
  },
  {
    pronoun: "I",
    verb: "Can",
    action: "Run",
    pronunciation: "/kæn/ (can) /rʌn/ (run)",
    translation: "I Can Run",
  },
  {
    pronoun: "I",
    verb: "Would like",
    action: "Sleep",
    pronunciation: "/aɪ wʊd laɪk/ (eye wood like) /sliːp/ (sleep)",
    translation: "I Would Like to Sleep",
  },
  {
    pronoun: "I",
    verb: "Think",
    action: "Drink",
    pronunciation: "/aɪ θɪŋk/ (eye think) /drɪŋk/ (drink)",
    translation: "I Think to Drink",
  },
  {
    pronoun: "I",
    verb: "Can",
    action: "Sleep",
    pronunciation: "/kæn/ (can) /sliːp/ (sleep)",
    translation: "I Can Sleep",
  },

  // Pronoun YOU
  {
    pronoun: "You",
    verb: "Would like",
    action: "Sleep",
    pronunciation: "/juː wʊd laɪk/ (you wood like) /sliːp/ (sleep)",
    translation: "You Would Like to Sleep",
  },
  {
    pronoun: "You",
    verb: "Would like",
    action: "Travel",
    pronunciation: "/juː wʊd laɪk/ (you wood like) /ˈtrævəl/ (travel)",
    translation: "You Would Like to Travel",
  },
  {
    pronoun: "You",
    verb: "Have",
    action: "To Drink",
    pronunciation: "/juː hæv/ (you have) /tuː drɪŋk/ (to drink)",
    translation: "You Have to Drink",
  },
  {
    pronoun: "You",
    verb: "Must",
    action: "Sleep",
    pronunciation: "/juː mʌst/ (you must) /sliːp/ (sleep)",
    translation: "You Must Sleep",
  },
  {
    pronoun: "You",
    verb: "Hope",
    action: "To Drink",
    pronunciation: "/juː hoʊp/ (you hope) /tuː drɪŋk/ (to drink)",
    translation: "You Hope to Drink",
  },
  {
    pronoun: "You",
    verb: "Think",
    action: "To Drink",
    pronunciation: "/juː θɪŋk/ (you think) /tuː drɪŋk/ (to drink)",
    translation: "You Think to Drink",
  },
  {
    pronoun: "You",
    verb: "Can",
    action: "Sleep",
    pronunciation: "/juː kæn/ (you can) /sliːp/ (sleep)",
    translation: "You Can Sleep",
  },

  // Pronoun HE
  {
    pronoun: "He",
    verb: "Would like",
    action: "Travel",
    pronunciation: "/hiː wʊd laɪk/ (he wood like) /ˈtrævəl/ (travel)",
    translation: "He Would Like to Travel",
  },
  {
    pronoun: "He",
    verb: "Needs",
    action: "To Write",
    pronunciation: "/hiːdz/ (he needs) /tuː raɪt/ (to write)",
    translation: "He Needs to Write",
  },
  {
    pronoun: "He",
    verb: "Needs",
    action: "To Write",
    pronunciation: "/hiːdz/ (he needs) /tuː raɪt/ (to write)",
    translation: "They Need to Write",
  },
  {
    pronoun: "He",
    verb: "Thinks",
    action: "To Write",
    pronunciation: "/hiː θɪŋks/ (he thinks) /tuː raɪt/ (to write)",
    translation: "He Thinks to Write",
  },
  {
    pronoun: "He",
    verb: "Can",
    action: "Travel",
    pronunciation: "/hiː kæn/ (he can) /ˈtrævəl/ (travel)",
    translation: "He Can Travel",
  },
  {
    pronoun: "He",
    verb: "Wants",
    action: "To Study",
    pronunciation: "/hiː wænts/ (he wants) /tuː ˈstʌdi/ (to study)",
    translation: "He Wants to Study",
  },

  // Pronoun WE
  {
    pronoun: "We",
    verb: "Need",
    action: "To Work",
    pronunciation: "/wiː niːd/ (we need) /tuː wɜːrk/ (to work)",
    translation: "We Need to Work",
  },
  {
    pronoun: "We",
    verb: "Would like",
    action: "To Dance",
    pronunciation: "/wiː wʊd laɪk/ (we wood like) /tuː dæns/ (to dance)",
    translation: "We Would Like to Dance",
  },
  {
    pronoun: "We",
    verb: "Must",
    action: "To Dance",
    pronunciation: "/wiː mʌst/ (we must) /tuː dæns/ (to dance)",
    translation: "We Must Dance",
  },
  {
    pronoun: "We",
    verb: "Hope",
    action: "To Work",
    pronunciation: "/wiː hoʊp/ (we hope) /tuː wɜːrk/ (to work)",
    translation: "We Hope to Work",
  },
  {
    pronoun: "We",
    verb: "Think",
    action: "To Work",
    pronunciation: "/wiː θɪŋk/ (we think) /tuː wɜːrk/ (to work)",
    translation: "We Think to Work",
  },
  {
    pronoun: "We",
    verb: "Can",
    action: "To Dance",
    pronunciation: "/wiː kæn/ (we can) /tuː dæns/ (to dance)",
    translation: "We Can Dance",
  },

  // Pronoun YOU (plural)
  {
    pronoun: "You",
    verb: "Would like",
    action: "",
    pronunciation: "/juː wʊd laɪk/ (you wood like)",
    translation: "You Would Like",
  },
  {
    pronoun: "You",
    verb: "Need",
    action: "To Read",
    pronunciation: "/juː niːd/ (you need) /tuː riːd/ (to read)",
    translation: "You Need to Read",
  },
  {
    pronoun: "You",
    verb: "Must",
    action: "",
    pronunciation: "/juː mʌst/ (you must)",
    translation: "You Must",
  },
  {
    pronoun: "You",
    verb: "Hope",
    action: "To Read",
    pronunciation: "/juː hoʊp/ (you hope) /tuː riːd/ (to read)",
    translation: "You Hope to Read",
  },
  {
    pronoun: "You",
    verb: "Think",
    action: "To Read",
    pronunciation: "/juː θɪŋk/ (you think) /tuː riːd/ (to read)",
    translation: "You Think to Read",
  },
  {
    pronoun: "You",
    verb: "Can",
    action: "",
    pronunciation: "/juː kæn/ (you can)",
    translation: "You Can",
  },

  // Pronoun THEY
  {
    pronoun: "They",
    verb: "Would like",
    action: "",
    pronunciation: "/ðeɪ wʊd laɪk/ (they wood like)",
    translation: "They Would Like",
  },
  {
    pronoun: "They",
    verb: "Must",
    action: "",
    pronunciation: "/ðeɪ mʌst/ (they must)",
    translation: "They Must",
  },
  {
    pronoun: "They",
    verb: "Need",
    action: "To Write",
    pronunciation: "/ðeɪ niːd/ (they need) /tuː raɪt/ (to write)",
    translation: "They Need to Write",
  },
  {
    pronoun: "They",
    verb: "Think",
    action: "To Write",
    pronunciation: "/ðeɪ θɪŋk/ (they think) /tuː raɪt/ (to write)",
    translation: "They Think to Write",
  },
  {
    pronoun: "They",
    verb: "Can",
    action: "",
    pronunciation: "/ðeɪ kæn/ (they can)",
    translation: "They Can",
  },
  {
    pronoun: "They",
    verb: "Want",
    action: "To Write",
    pronunciation: "/ðeɪ wænt/ (they want) /tuː raɪt/ (to write)",
    translation: "They Want to Write",
  },
];

export default matrizEng;
